### ISSUE TITLE
Перестал работать, как обновить.

### ISSUE THREAD

**Issue by CIRTechnology** [xtrime-ru/TelegramRSS#19]
Здравствуйте, 2 месяца назад всё работало, а теперь при запуске  [critical] SESSION_REVOKED
Возможно, что нужно обновить, обновление это команды в заголовке Upgrade to v4? Но не помогает, помогите, пожалуйста, как это исправить?
``` 
[2024-05-19 09:30:02] [warning] Connecting to DC 2
[2024-05-19 09:30:02] [warning] Resetting session in DC 2.0...
[2024-05-19 09:30:02] [warning] Connecting to DC 2.0 via tcp://149.154.167.41:443 main DC 2,                                  via ipv4 using AbridgedStream => BufferedRawStream => DefaultStream
[2024-05-19 09:30:02] [warning] Connected to DC 2.0 via tcp://149.154.167.41:443 main DC 2,                                  via ipv4 using AbridgedStream => BufferedRawStream => DefaultStream!
[2024-05-19 09:30:03] [critical] SESSION_REVOKED
[2024-05-19 09:30:13] [error] Still missing users.getUsers, auth.logOut,  on DC 2.0, sending                                  state request
[2024-05-19 09:30:18] [critical] Reporting: Amp\TimeoutException: Request timeout in /app-ho                                 st-link/vendor/danog/madelineproto/src/MTProtoSession/AckHandler.php:125
Stack trace:
#0 /app-host-link/vendor/danog/madelineproto/src/WrappedFuture.php(59): danog\MadelineProto\                                 Connection::danog\MadelineProto\MTProtoSession\{closure}()
#1 /app-host-link/vendor/danog/madelineproto/src/MTProtoSession/CallHandler.php(92): danog\M                                 adelineProto\WrappedFuture->await()
#2 /app-host-link/vendor/danog/madelineproto/src/MTProtoTools/CallHandler.php(45): danog\Mad                                 elineProto\Connection->methodCallAsyncRead('users.getUsers', Array)
#3 /app-host-link/vendor/danog/madelineproto/src/MTProto.php(1470): danog\MadelineProto\MTPr                                 oto->methodCallAsyncRead('users.getUsers', Array)
#4 /app-host-link/vendor/danog/madelineproto/src/MTProto.php(1014): danog\MadelineProto\MTPr                                 oto->fullGetSelf()
#5 /app-host-link/vendor/danog/madelineproto/src/API.php(338): danog\MadelineProto\MTProto->                                 wakeup(Object(danog\MadelineProto\Settings), Object(danog\MadelineProto\APIWrapper))
#6 /app-host-link/vendor/danog/madelineproto/src/API.php(194): danog\MadelineProto\API->conn                                 ectToMadelineProto(Object(danog\MadelineProto\Settings))
#7 /app-host-link/src/Client.php(68): danog\MadelineProto\API->__construct('sessions/sessio.                                 ..', Object(danog\MadelineProto\Settings))
#8 /app-host-link/src/Client.php(37): TelegramApiServer\Client->addSession('session')
#9 /app-host-link/src/Server/Server.php(47): TelegramApiServer\Client->connect(Array)
#10 /app-host-link/server.php(107): TelegramApiServer\Server\Server->__construct(Array, Arra                                 y)
#11 {main}
[2024-05-19 09:30:18] [critical] Amp\TimeoutException: Request timeout in /app-host-link/ven                                 dor/danog/madelineproto/src/MTProtoSession/AckHandler.php:125
Stack trace:
#0 /app-host-link/vendor/danog/madelineproto/src/WrappedFuture.php(59): danog\MadelineProto\                                 Connection::danog\MadelineProto\MTProtoSession\{closure}()
#1 /app-host-link/vendor/danog/madelineproto/src/MTProtoSession/CallHandler.php(92): danog\M                                 adelineProto\WrappedFuture->await()
#2 /app-host-link/vendor/danog/madelineproto/src/MTProtoTools/CallHandler.php(45): danog\Mad                                 elineProto\Connection->methodCallAsyncRead('users.getUsers', Array)
#3 /app-host-link/vendor/danog/madelineproto/src/MTProto.php(1470): danog\MadelineProto\MTPr                                 oto->methodCallAsyncRead('users.getUsers', Array)
#4 /app-host-link/vendor/danog/madelineproto/src/MTProto.php(1014): danog\MadelineProto\MTPr                                 oto->fullGetSelf()
#5 /app-host-link/vendor/danog/madelineproto/src/API.php(338): danog\MadelineProto\MTProto->                                 wakeup(Object(danog\MadelineProto\Settings), Object(danog\MadelineProto\APIWrapper))
#6 /app-host-link/vendor/danog/madelineproto/src/API.php(194): danog\MadelineProto\API->conn                                 ectToMadelineProto(Object(danog\MadelineProto\Settings))
#7 /app-host-link/src/Client.php(68): danog\MadelineProto\API->__construct('sessions/sessio.                                 ..', Object(danog\MadelineProto\Settings))
#8 /app-host-link/src/Client.php(37): TelegramApiServer\Client->addSession('session')
#9 /app-host-link/src/Server/Server.php(47): TelegramApiServer\Client->connect(Array)
#10 /app-host-link/server.php(107): TelegramApiServer\Server\Server->__construct(Array, Arra                                 y)

```

**Comment by xtrime-ru** [comment]
Проблема исправлена в последнем коммите https://github.com/xtrime-ru/TelegramApiServer

Нужно обновить его вот так: 
```
cd ../TelegramApiServer/
docker compose down
git pull
rm -rf vendor/
docker compose pull
docker compose up -d
```

При обновлении будут запущены миграции в базе,  поэтому лучше сначала сделать бекап базы и закоментировать healthcheck в файле docker-compose.base.yml, что бы контейнер не убило во время миграции.

**Comment by xtrime-ru** [comment]
Что касается SESSION_REVOKED, то вероятно нужно удалить папку sessions/madeline.session/ (и возможно таблицу *_session в mysql и авторизоваться заново. 

Возможно, что аккаунт совсем заблокирован и нужно писать email: https://docs.madelineproto.xyz/docs/LOGIN.html#getting-permission-to-use-the-telegram-api
